---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos
    image: centos:8
    pre_build_image: true
  - name: ubuntu
    image: python
    pre_build_image: true
  - name: Redhat
    image: redhat/ubi8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
